version: '3.8'

services:
  # Servicio de la Base de Datos
  db-postgres:
    image: postgres:15-alpine
    container_name: postgres-pokedex
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Te permite conectar pgAdmin desde tu computadora externa
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de tu Aplicación Spring Boot
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokemon-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db-postgres # Apunta al nombre del servicio de arriba
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=postgres
    depends_on:
      - db-postgres # Espera a que el contenedor de la BD levante antes de iniciar la app

volumes:
  postgres_data: # Mantiene tus datos guardados aunque apagues los contenedores
