spring:
  application:
    name: pokedex
  datasource:
    # CORREGIDO: Cambiamos localhost por db-postgres (el nombre en tu docker-compose)
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}?createDatabaseIfNotExist=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
